project:
  type: book
  output-dir: docs

book:
  title: "Subradiant CBS"
  author: "Some People"
  date: "8/18/2022"
  chapters:
    - index.qmd
    - 01_double_scattering.qmd
    - 02_two_atom_appr.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
